import{i as c,S as l}from"./assets/vendor-5b791d57.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();function p(s){const e=`https://pixabay.com/api/?key=43022470-1213c485ef19c9845e2639418&q=${s}&image_type=photo&orientation=horizontal&safesearch=true`;return fetch(e).then(t=>t.json())}function u({webformatURL:s,tags:r,views:i,likes:n,comments:e,downloads:t,largeImageURL:a}){return`<li class="image-item">
  <a class="image-link" href="${a}">
  <img src="${s}" alt="${r}" width ="300" height="200" ></a>
  <div class="tex-container">
  <p class="image-text">Likes <span class="span-text">${n}</span></p>
  <p class="image-text">Views <span class="span-text">${i}</span></p>
  <p class="image-text">Comments <span class="span-text">${e}</span></p>
  <p class="image-text">Downloads <span class="span-text">${t}</span></p>
  </div>
</li>`}function m(s){return s.map(u).join("")}function f(){return'<span class="loader">Loading</span>'}function g(){return'<span class="error">ERROR</span>'}const o=document.querySelector(".image-list"),d=document.querySelector(".form-search");d.addEventListener("submit",h);function h(s){s.preventDefault();const r=s.target.elements.search.value.trim(2,0);if(!r)return;o.innerHTML="";const i=Date.now();o.insertAdjacentHTML("afterbegin",f()),p(r).then(n=>{const e=Date.now()-i;setTimeout(()=>{if(!n.hits.length)o.innerHTML="",c.show({position:"topRight",color:"red",messageColor:"black",message:"Sorry, there are no images matching your search query. Please try again!"});else{const t=m(n.hits);o.innerHTML=t,new l(".image-link",{captionsData:"alt",captionDelay:250}).refresh()}},e)}).catch(()=>{o.insertAdjacentHTML("afterbegin",g())}),s.target.reset()}
//# sourceMappingURL=commonHelpers.js.map
